# Generated by Django 6.1.1 on 2026-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name (max 100 characters)', max_length=100)),
                ('job_title', models.CharField(help_text='Job role or position title (max 150 characters)', max_length=150)),
                ('application_date', models.DateField(help_text='Date when application was submitted')),
                ('job_type', models.CharField(choices=[('Internship', 'Internship'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], default='Internship', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text='Location e.g. Bangalore, Remote', max_length=100)),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On-site', 'On-site')], default='Hybrid', max_length=20)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Online Assessment', 'Online Assessment'), ('Interview', 'Interview'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=30)),
                ('application_url', models.URLField(blank=True, default='', help_text='Direct link to job posting or application portal', max_length=500)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes e.g. interview stages, contact details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-application_date', '-created_at'],
            },
        ),
    ]
